### ISSUE TITLE
Fails to download when...

### ISSUE THREAD

**Issue by ValentinJesse** [dsoprea/youtube-autodownloader#1]
The script is successfully downloading the playlists up to the point where it encounters videos that were taken down with "This video is no longer available due to a copyright claim by ..." and then it stops instead of skipping. It's probably doing the same with other errors like "not available in your country", i didn't test it extensively.

**Comment by dsoprea** [comment]
Can you provide output?

**Comment by ValentinJesse** [comment]
```Top xxxxxx
- Playlist: xxxxxxx
- ID: hbSh_XDL4rE
ERROR:hbSh_XDL4rE: YouTube said: "Top xxxxxx ..." This video is no longer available due to a copyright claim by UDY.
Traceback (most recent call last):
  File "/usr/local/bin/ytad_autodownload", line 4, in <module>
    __import__('pkg_resources').run_script('youtube-autodownloader==0.2.4', 'ytad_autodownload')
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 739, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1494, in run_script
    exec(code, namespace, namespace)
  File "/Library/Python/2.7/site-packages/youtube_autodownloader-0.2.4-py2.7.egg/EGG-INFO/scripts/ytad_autodownload", line 74, in <module>
    _main()
  File "/Library/Python/2.7/site-packages/youtube_autodownloader-0.2.4-py2.7.egg/EGG-INFO/scripts/ytad_autodownload", line 71, in _main
    d.check_and_download(playlist_id, download_path=args.download_path)
  File "/Library/Python/2.7/site-packages/youtube_autodownloader-0.2.4-py2.7.egg/ytad/download.py", line 149, in check_and_download
    print_output=print_output)
  File "/Library/Python/2.7/site-packages/youtube_autodownloader-0.2.4-py2.7.egg/ytad/download.py", line 68, in _download_one
    ydl.download([url])
  File "/Library/Python/2.7/site-packages/youtube_dl-2018.2.26-py2.7.egg/youtube_dl/YoutubeDL.py", line 1989, in download
    url, force_generic_extractor=self.params.get('force_generic_extractor', False))
  File "/Library/Python/2.7/site-packages/youtube_dl-2018.2.26-py2.7.egg/youtube_dl/YoutubeDL.py", line 808, in extract_info
    self.report_error(compat_str(e), e.format_traceback())
  File "/Library/Python/2.7/site-packages/youtube_dl-2018.2.26-py2.7.egg/youtube_dl/YoutubeDL.py", line 613, in report_error
    self.trouble(error_message, tb)
  File "/Library/Python/2.7/site-packages/youtube_dl-2018.2.26-py2.7.egg/youtube_dl/YoutubeDL.py", line 583, in trouble
    raise DownloadError(message, exc_info)
youtube_dl.utils.DownloadError: ERROR: hbSh_XDL4rE: YouTube said: "Top xxxxxx ..." This video is no longer available due to a copyright claim by UDY.

**Comment by dsoprea** [comment]
There was actually already a fix for this in the project, but it was unreleased into PyPI. I just pushed an update.

**Comment by ValentinJesse** [comment]
Thanks for the prompt response and for the effort in creating this script.

Git pulled the changes, reinstalled, ran the script again, downloaded 20-30 videos (successfully skipped the unavailable ones) and then returned this:

```
Traceback (most recent call last):
  File "/usr/local/bin/ytad_autodownload", line 4, in <module>
    __import__('pkg_resources').run_script('youtube-autodownloader==0.2.5', 'ytad_autodownload')
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 739, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1494, in run_script
    exec(code, namespace, namespace)
  File "/Library/Python/2.7/site-packages/youtube_autodownloader-0.2.5-py2.7.egg/EGG-INFO/scripts/ytad_autodownload", line 74, in <module>
    _main()
  File "/Library/Python/2.7/site-packages/youtube_autodownloader-0.2.5-py2.7.egg/EGG-INFO/scripts/ytad_autodownload", line 71, in _main
    d.check_and_download(playlist_id, download_path=args.download_path)
  File "/Library/Python/2.7/site-packages/youtube_autodownloader-0.2.5-py2.7.egg/ytad/download.py", line 150, in check_and_download
    playlist = pa.get_with_id(playlist_id)
  File "/Library/Python/2.7/site-packages/youtube_autodownloader-0.2.5-py2.7.egg/ytad/accessor/playlists.py", line 49, in get_with_id
    response = self._list_with_id(id)
  File "/Library/Python/2.7/site-packages/youtube_autodownloader-0.2.5-py2.7.egg/ytad/entity_registry.py", line 24, in wrapper
    request = f(self, *args, **kwargs)
  File "/Library/Python/2.7/site-packages/youtube_autodownloader-0.2.5-py2.7.egg/ytad/accessor/playlists.py", line 39, in _list_with_id
    client = self.__cm.get_client()
  File "/Library/Python/2.7/site-packages/googleautoauth-0.2.9-py2.7.egg/googleautoauth/client_manager.py", line 119, in get_client
    self.__service_version)
  File "/Library/Python/2.7/site-packages/googleautoauth-0.2.9-py2.7.egg/googleautoauth/authorize.py", line 217, in get_client
    self._get_token().authorize(http)
  File "/Library/Python/2.7/site-packages/googleautoauth-0.2.9-py2.7.egg/googleautoauth/authorize.py", line 157, in _get_token
    self._check_for_renew(self._token)
  File "/Library/Python/2.7/site-packages/googleautoauth-0.2.9-py2.7.egg/googleautoauth/authorize.py", line 120, in _check_for_renew
    token.refresh(http)
  File "build/bdist.macosx-10.13-intel/egg/oauth2client/client.py", line 633, in refresh
  File "build/bdist.macosx-10.13-intel/egg/oauth2client/client.py", line 842, in _refresh
  File "build/bdist.macosx-10.13-intel/egg/oauth2client/client.py", line 874, in _do_refresh_request
  File "/Library/Python/2.7/site-packages/httplib2-0.10.3-py2.7.egg/httplib2/__init__.py", line 1659, in request
    (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
  File "/Library/Python/2.7/site-packages/httplib2-0.10.3-py2.7.egg/httplib2/__init__.py", line 1399, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "/Library/Python/2.7/site-packages/httplib2-0.10.3-py2.7.egg/httplib2/__init__.py", line 1319, in _conn_request
    conn.connect()
  File "/Library/Python/2.7/site-packages/httplib2-0.10.3-py2.7.egg/httplib2/__init__.py", line 1069, in connect
    self.ssl_version, self.host)
  File "/Library/Python/2.7/site-packages/httplib2-0.10.3-py2.7.egg/httplib2/__init__.py", line 97, in _ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=hostname)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py", line 352, in wrap_socket
    _context=self)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py", line 579, in __init__
    self.do_handshake()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py", line 808, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:590)
```

Any workaround for this ? I'm running it on macOS High Sierra

**Comment by dsoprea** [comment]
Try it again. Seems like a network burp.

**Comment by ValentinJesse** [comment]
Thanks for the support!
